FROM node:14.15.3-alpine3.12

COPY package.json \
	 yarn.lock \
	 tsconfig.json \
	 tsconfig.build.json \
     /usr/src/app/

ADD .env /usr/src/app/

RUN cd /usr/src/app/  && yarn install --frozen-lockfile && npm i ts-node -g

WORKDIR /usr/src/app/

CMD node --inspect=9229 -r ts-node/register src/BootstrapFullEgripData.ts
